### ISSUE TITLE
Label that should be zero shows ratios up to 50%?

### ISSUE THREAD

**Issue by sorenwacker** [compomics/reporter#10]
We have a test plate that was done with 10 of the 11plex TMT labels. So, the intensities of the 11th label should be almost zero, plus the leakage from the 10th label due to 13C content. Although we observe a substantial drop in the intensities, we see ratios up to 50 percent compared to the highest reference intensity, which is the maximum of the intensities of the other labels. Is that something you would expect? Is this due to the normalization?

I was using Reporter 0.7.17 from command line without specifying a reference sample. Pretty much default configuration, created the default protein report.

**Comment by mvaudel** [comment]
Indeed the default normalization can create such discrepancies, as it will put the median of the ratios for a channel to 1:1. In that case if you are interested in the values of channel 11 you might want to use "No normalization", or provide a list of seed proteins that are expected to be 1:1. 
Please note that contribution of 13C from channel 10 should be corrected by the normalization factors, and should be much lower than 50%. If you see such intensities in the raw (ie not normalized) ratios, it is more likely to be co-isolated peptides.

**Comment by soerendip** [comment]
Thanks for the clarification. Could you explain that normalization a bit more? The median of what exactly? Is this per label normalization? If yes, I wonder why we get always the highest sum of rations for the first label.
