### ISSUE TITLE
CLI options display

### ISSUE THREAD

**Issue by heckendorfc** [compomics/reporter#20]
https://github.com/compomics/reporter/blob/a7e09fc5844f63e86344f0fbd1e3c2efd14d757e/src/main/java/eu/isas/reporter/cli/ReporterCLIParameters.java#L132

I think this line is supposed to say "replace eu.isas.reporter.cli.ReporterCLI with eu.isas.reporter.cli.ReportCLI"

**Comment by hbarsnes** [comment]
Yes, you are right! It has now been corrected in the code and will thus be fixed in the next release of Reporter. Thanks for letting us know!
