### ISSUE TITLE
An error occurred while generating the output

### ISSUE THREAD

**Issue by davidserv** [compomics/reporter#4]
Hello,

For several samples Reporter gives me this error message (in the title of this issue) for no obvious reason. They were created on a Galaxy instance wiht SearchGUI 3.2.13.4 and PeptideShaker 1.16.17.

Here is a sample I gave as an input file to Reporter: https://drive.google.com/file/d/19XjNknhqBE1qhEhWPTQZF5C7IpqM6Xtw

Is it because Reporter can't read output of old SearchGUI and PeptideShaker versions ?

Best regards,
David S.

**Comment by hbarsnes** [comment]
Hi David,

Seems like you are not using the correct FASTA file? At least I get the following error (as detailed in the Reporter log file) when exporting the peptides: "Protein not found: P22413_REVERSED". In other words, it seems like you give Reporter the FASTA file without the decoys, while the one used in PeptideShaker included the decoys? If you correct this it should solve the problem.

Best regards,
Harald

**Comment by davidserv** [comment]
Indeed, the decoy database did the job.

Many thanks !

David S.
