### ISSUE TITLE
Isotopes XML file

### ISSUE THREAD

**Issue by iquasere** [compomics/reporter#6]
Greetings

I'm trying to perform quantification with ReporterCLI, and would like to know if there is an example available of an isotope correction factors xml file to give as input. Are these files usually supplied by the laboratories performing the mass spectrometry? Also, what separates the "isotopes" file from the "methods_file"?

Thank you for your attention

**Comment by hbarsnes** [comment]
Hi,

> an example available of an isotope correction factors xml file to give as input

All of this information should be in the file Reporter-X.Y.Z\resources\conf\defaultMethods.xml. 

> Are these files usually supplied by the laboratories performing the mass spectrometry?

Yes, they come with the TMT kit.

>  Also, what separates the "isotopes" file from the "methods_file"?

Not really sure what you are referring to here? Is this from the documentation of the code?

In any case, please note that the command line support for Reporter is still very much in development. Not even sure if it has been fully tested yet. So probably recommended to stay with the graphical user interface for now is possible.

Best regards,
Harald

**Comment by iquasere** [comment]
>Not really sure what you are referring to here? Is this from the documentation of the code?

As of version 0.7.15, the help message is as follows
```
======================
ReporterCLI
======================

ReporterCLI estimates abundance ratios from PeptideShaker projects based on reporter ion quantification.

For further help see https://compomics.github.io/projects/reporter.html and https://compomics.github.io/projects/reporter/wiki/reportercli.html.

Or contact the developers at https://groups.google.com/group/reporter.

----------------------
OPTIONS
----------------------

Mandatory Parameters:

-id                        The PeptideShaker project (.cpsx or .zip).
-isotopes                  The isotope correction factors file (.xml file). Default values used if not provided. It is strongly advised to provide the values corresponding to the labelling kit used during the experiment.
Reporter Ion Methods options:

-methods_file              Path to the isotope correction factors file containing the quantification methods including isotopic correction factors. Default values used if not provided.
-method                    The reporter ion quantification method to use from the isotopic methods file in case multiple methods are listed in the file. Inferred from the identification parameters if not provided.


Output:

-out                       Output file to save the project.


Optional Export Parameters:

-zip                       Exports the entire project as a zip file in the file specified.


Processing Options:

-threads                   Number of threads to use for the processing, default: the number of cores on the machine.


Advanced Options:



Optional Temporary Folder:

-temp_folder               A folder for temporary file storage. Use only if you encounter problems with the default configuration.


Optional Input Parameters:

-id_params                 The identification parameters file to use.



For identification parameters options:
Replace eu.isas.reporter.cmd.ReporterCLI with eu.isas.reportergui.cmd.IdentificationParametersCLI


For report export options:
Replace eu.isas.reporter.cli.ReporterCLI with eu.isas.reporter.cli.ReporterCLI
```

Here, the "-isotopes" and "-methods_file" parameters seem to reference to the same file.

**Comment by hbarsnes** [comment]
Hi again,

As expected -isotopes and -methods_file referred to the same file and the command line was simply never updated. Told you the command lines were not fully tested yet. ;)

Anyway, I've just deployed a new version of Report where only the -isotopes option remains. No guarantees that there aren't other issues with the command line though. So if you come across any, please open a new issue. :)

Best regards,
Harald
