### ISSUE TITLE
Manual available?

### ISSUE THREAD

**Issue by soerendip** [compomics/reporter#7]
We are trying to find a manual, documentation for Reporter. Is it able to do TMT11plex MS3 quantification?
kind regards

**Comment by hbarsnes** [comment]
I'm afraid there is currently no manual for Reporter as it is still in development.

Regarding TMT 11-plex, Reporter does support 11-plex, but only based on MS2 quantification not MS3.

**Comment by soerendip** [comment]
Thanks!
