### ISSUE TITLE
How to export TMT11plex quantification?

### ISSUE THREAD

**Issue by soerendip** [compomics/reporter#8]
I wonder whether it is possible to export the quantification results from shaker. I saw the reports that can be exported, but they seem to be identical to the once that PeptideShaker creates? Ideally, I am looking for a way to do export the quantification data from the commandline in linux.

**Comment by hbarsnes** [comment]
Reporter does have its own command line support:

- run `java -cp Reporter-0.7.16.jar eu.isas.reporter.cli.ReporterCLI` to see the options for quantifiying the data
- and run `java -cp Reporter-0.7.16.jar eu.isas.reporter.cli.ReportCLI` to see the report options

It should also be possible to attach the -reports options from ReportCLI directly to the ReporterCLI command line.

And while the names of the reports may be the same as for PeptideShaker, they should contain extra columns with the quantification data.

Note however that the command line support for Reporter it is still in beta mode and yet not fully tested.

**Comment by soerendip** [comment]
When I run 

`java -cp ~/Software/Reporter/Reporter-0.7.16/Reporter-0.7.16.jar eu.isas.reporter.cli.ReportCLI -id "/home/.../workspace/uofc/lsarp/proteomics/0002-D003_MS2-TMT/run/S8926_A_TMT_T_MS2_181116/TMT11a/proteinshaker.cpsx" -reports "1,2,3,4,5,6,7,8,9,10,11" -out_reports "/home/../workspace/uofc/lsarp/proteomics/0002-D003_MS2-TMT/run/S8926_A_TMT_T_MS2_181116/TMT11a/reporter/"`

I get :
> <CompomicsError>Reporter processing failed. See the Reporter log for details.</CompomicsError>
But there is no log file. Not in the working directory and not where the Reporter jar file sits.

**Comment by soerendip** [comment]
I found the log file.

> Thu Feb 14 09:41:06 MST 2019: Reporter version 0.7.16.
Memory given to the Java virtual machine: 16869490688 b.
Total amount of memory in the Java virtual machine: 1056964608 b.
Free memory: 1047567112 b.
Java version: 11.0.1.
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -id
	at org.apache.commons.cli.Parser.processOption(Parser.java:363)
	at org.apache.commons.cli.Parser.parse(Parser.java:199)
	at org.apache.commons.cli.Parser.parse(Parser.java:85)
	at eu.isas.reporter.cli.ReportCLI.main(ReportCLI.java:276)

**Comment by soerendip** [comment]
So, it is not doing anything. And I get a message in the log file: 

> Thu Feb 14 13:15:42 MST 2019: Reporter version 0.7.16.
Memory given to the Java virtual machine: 16869490688 b.
Total amount of memory in the Java virtual machine: 1056964608 b.
Free memory: 1047567296 b.
Java version: 11.0.2.

Using java:

> java version "11.0.2" 2018-10-16 LTS
> Java(TM) SE Runtime Environment 18.9 (build 11.0.2+7-LTS)
> Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+7-LTS, mixed mode)
>

**Comment by soerendip** [comment]
I am trying to convert the file with Reporter using 
`java -cp ~/Software/Reporter/Reporter-0.7.16/Reporter-0.7.16.jar eu.isas.reporter.cli.ReporterCLI -in ".../peptideshaker.cpsx" -zip ".../reporter.zip"``

The log file shows that these keywords `-zip` or `-out` are not known.

**Comment by soerendip** [comment]
I opened the peptideshaker.cpsx with reporter and safed the project as reporter.cpsx. Then tried it to process it, but I get the same error message about file incompatibility.

**Comment by hbarsnes** [comment]
Seems like I introduced a bug in recent code clean up were I mixed the parameters for ReportCLI and ReporterCLI. I will correct this and release a new version of Reporter as soon as possible.

After this fix a command line of the following type should work:
`java -cp Reporter-0.7.17.jar eu.isas.reporter.cli.ReporterCLI -id C:\...\PeptideShaker_output.cpsx -isotopes C:\...\Reporter-0.7.17\resources\conf\defaultMethods.xml -method "TMT 10-plex" -out C:\...\tmt.cpsx`

**Comment by hbarsnes** [comment]
Just released [Reporter v0.7.17](http://genesis.ugent.be/maven2/eu/isas/reporter/Reporter/0.7.17/Reporter-0.7.17.zip) which should solve the issues with the command line.

Here's the kind of command line that now works fine for me:
`java -cp Reporter-0.7.17.jar eu.isas.reporter.cli.ReporterCLI -id C:\...\PeptideShaker_output.cpsx -isotopes C:\...\Reporter-0.7.17\resources\conf\defaultMethods.xml -method "TMT 10-plex" -out C:\...\tmt.cpsx -ref_samples 1 -reports 9`

**Comment by soerendip** [comment]
Where is that defaultMethods.xml file coming from?

**Comment by soerendip** [comment]
I can create a bunch of reports from the commandline now, but I don't find the quantification data. 
This is the list of files that was generated:

> Default_Hierarchical_Report.txt
> Default_Peptide_Phosphorylation_Report.txt
> Default_Peptide_Report.txt
> Default_Peptide_Report_with_non-validated_matches.txt
> Default_Protein_Phosphorylation_Report.txt
> Default_Protein_Report.txt
> Default_Protein_Report_with_non-validated_matches.txt
> Default_PSM_Phosphorylation_Report.txt
> Default_PSM_Report.txt
> Default_PSM_Report_with_non-validated_matches.txt
> Extended_PSM_Report.txt

Which of these files should contain the quantification data and which columns would that be?

**Comment by hbarsnes** [comment]
All of these should contain the quantification data. There should be columns with this data to the far right in the reports. Are you saying that these columns are not there? If so, maybe you can share your Default Protein Report?

**Comment by soerendip** [comment]
The column names would be helpful. I have these columns:
Unnamed: 0
Main Accession
Description
Gene Name
Chromosome
Protein Inference
Secondary Accessions
Protein Group
#Peptides
#Validated Peptides
#Unique
#Validated Unique
#Unique to Group
#Validated Unique to Group
#PSMs
#Validated PSMs
Coverage [%]
Possible Coverage [%]
MW [kDa]
Spectrum Counting
Confidently Localized Modification Sites
# Confidently Localized Modification Sites
Ambiguously Localized Modification Sites
#Ambiguously Localized Modification Sites
Confidence [%]
Validation
Raw Unique Ratios
 
 .1
 .2
 .3
 .4
 .5
 .6
 .7
 .8
 .9
Raw Shared Ratios
 .10
 .11
 .12
 .13
 .14
 .15
 .16
 .17
 .18
 .19
Raw Ratios
 .20
 .21
 .22
 .23
 .24
 .25
 .26
 .27
 .28
 .29
Unique Ratios
 .30
 .31
 .32
 .33
 .34
 .35
 .36
 .37
 .38
 .39
Shared Ratios
 .40
 .41
 .42
 .43
 .44
 .45
 .46
 .47
 .48
 .49
Ratios
 .50
 .51
 .52
 .53
 .54
 .55
 .56
 .57
 .58
 .59

I have 11plex data. So I expect 11 columns for quantification?

**Comment by hbarsnes** [comment]
> I have 11plex data. So I expect 11 columns for quantification?

TMT is generally used as relative quantification, i.e. you retain one TMT tag for the reference sample that you divide the values from the other TMT tags on to make them comparable. Hence you will have ten ratios for 11plex, nine ratios for 10plex etc.

The references sample is set by using the -ref_samples option.

**Comment by soerendip** [comment]
Alright. Thanks!
