### ISSUE TITLE
raw/corrected TMT intensities with reporter

### ISSUE THREAD

**Issue by korbini** [compomics/reporter#9]
Hi, is it possible to export raw/corrected TMT intensities with reporter? I haven't seen an option for this. It would be nice for further processing with e.g. limma.

**Comment by hbarsnes** [comment]
Hi,

Yes, this is support both via Export > Quantification Features in the graphical user interface or via the command line. For the command line option, please see this recent discussion: https://github.com/compomics/reporter/issues/8.

Best regards,
Harald

**Comment by korbini** [comment]
Hi thank you for your quick response.
If I am not mistaken reporter only exports ratios and not intensities. - Or maybe I have missed something.

**Comment by hbarsnes** [comment]
> If I am not mistaken reporter only exports ratios and not intensities

If you don't select a reference sample you should get just the intensities. I think. :)

**Comment by korbini** [comment]
Looks like ratios to me (also says in row above) :(

**Comment by hbarsnes** [comment]
Not sure how it can be ratios when there is nothing to divide them on? (i.e. no reference sample)

**Comment by korbini** [comment]
These one digit values look like ratios IMHO (example attached). Could it be ratios to median/mean?
I would be interested in the raw TMT signal intensity.

[AGLGSPERPPK.pdf](https://github.com/compomics/reporter/files/2900910/AGLGSPERPPK.pdf)
[AGLGSPERPPK.xlsx](https://github.com/compomics/reporter/files/2900914/AGLGSPERPPK.xlsx)

**Comment by hbarsnes** [comment]
Yes, you are correct. The intensities are by default normalized relative to the median for the peptides and the proteins, but not for the PSMs.

You can control this via the graphical user interface via the Advanced Settings at the bottom of the New Project dialog. Click the Edit button next to the Quantification field and then select normalization. There you can choose the normalization option for each level, or turn it off.

From the command line see the options normalization_psm, normalization_peptide and normalization_protein.

**Comment by korbini** [comment]
Thank you! Forgot about these.

**Comment by soerendip** [comment]
Is there are place where the normalization is formally written down anywhere?

**Comment by mvaudel** [comment]
I am afraid there is currently no detailed documentation on this. We are working on a major update of our code, we will update the documentation after this.
